### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PureEvilWindom** [LightningDragon/SVToggleTranscode#1]
the tool crash after map selection
![crash](https://cloud.githubusercontent.com/assets/16593879/12171593/be28f2c0-b57d-11e5-916e-bc9916ca9900.png)

**Comment by LightningDragon** [comment]
It looks like you forgot to transcode something. Please load your backup and follow the instructions exactly http://www.amecha.co.uk/forum/index.php?topic=3232.msg107063#msg107063 if this doesn't work please let me know.

**Comment by PureEvilWindom** [comment]
maybe too late but the tool works fine now by reinstalling the SV.
